apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name | quote }}
  labels:
    db: {{ .Values.db.name | quote }}
spec:
  ports:
    - port: {{ .Values.db.port }}
  selector:
    db: {{ .Values.db.name | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.componentName | quote }}
  labels:
    app: {{ .Values.global.componentName | quote }}
spec:
  ports:
    - port: {{ .Values.wordpress.port }}
  selector:
    app: {{ .Values.global.componentName | quote }}
  type: {{ .Values.wordpress.serviceType }}